vich_uploader:
    db_driver: orm

    mappings:
        item_files:
            uri_prefix: /items
            upload_destination: '%kernel.project_dir%/public/items'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
